### ISSUE TITLE
Obrázky s paralaxou

### ISSUE THREAD

**Issue by rampaq** [rampaq/talented#7]
Momentální skript vyžaduje starou verzi jQuery a s novou verzí nefunguje.
+ najít jiný skript, který umožňuje efekt paralaxy s obrázky – jestli bude potřebovat jQuery (JavaScript knihovna), tak pouze verzi >= 3.0.0

**Comment by polach** [comment]
Zkus tohle https://github.com/MoOx/parallaxify
